[general]
logging_level = "INFO"
database_path = "glasnost.db"

[credentials]
telegram = "TOKEN"
discord = "TOKEN"

[channel_ids]
telegram = -10012345
discord = [ 1234, 5678, 9012,]

[users]
ignored_users = []
listened_users = []

[bot_settings]
command_prefix = "!"
activity_status = "Missä mennään ja minne"
dm_only_commands = true

[preferences]
display_message_sender = false
prefer_telegram_usernames = true
send_orphans_as_new_message = true
message_cleanup_threshold = 30
update_age_threshold = 600
